import type {
  AskResponse,
  ChartFact,
  IChingResult,
  Insight,
  LifeDomain,
  Product,
  Recommendation,
  TimingPeriod,
} from "./types";

export const demoProfile = {
  id: "profile-yu-demo",
  displayName: "Yu",
  birthDate: "1990-06-17",
  birthTime: "09:32",
  birthLocation: "Shanghai, China",
  locale: "zh-CN",
  fixtureStatus: "fixture-not-calculated" as const,
};

export const facts: ChartFact[] = [
  {
    id: "fact-bazi-daymaster-yi-wood",
    system: "bazi",
    domain: "identity",
    scope: "natal",
    label: "乙木日主",
    rawLabel: "Day Master: Yin Wood",
    traditionalInterpretation: "传统上常用来讨论柔韧、适应和持续生长的方式。",
  },
  {
    id: "fact-bazi-wood-relative-low",
    system: "bazi",
    domain: "inner-life",
    scope: "natal",
    label: "木的相对呈现较弱",
    rawLabel: "Relative Wood presence: lower",
    traditionalInterpretation: "这不是缺陷；演示解释提示为成长、恢复和长期培育留出空间。",
    limitations: "元素权重是演示值，未经过真实排盘。",
  },
  {
    id: "fact-bazi-output-structure-tension",
    system: "bazi",
    domain: "career",
    scope: "natal",
    label: "表达动力与结构要求同时突出",
    rawLabel: "Demo pattern: expression × structure",
    traditionalInterpretation: "传统解释会把它看作创造冲动与规则、责任之间的持续协商。",
  },
  {
    id: "fact-bazi-current-month-focus",
    system: "bazi",
    domain: "timing",
    scope: "current-period",
    label: "当前月份强调取舍",
    rawLabel: "Demo monthly signal: focus and selection",
    traditionalInterpretation: "演示规则将这一时期解释为先收束资源、再决定投入方向。",
    limitations: "固定演示文案，并非真实流月计算。",
  },
  {
    id: "fact-ziwei-life-leadership",
    system: "ziwei",
    domain: "identity",
    scope: "natal",
    label: "命宫紫微、七杀",
    rawLabel: "Life Palace: Zi Wei + Qi Sha",
    traditionalInterpretation: "传统上常用于讨论自主判断、承担压力和重新组织局面的能力。",
  },
  {
    id: "fact-ziwei-career-tianji-authority",
    system: "ziwei",
    domain: "career",
    scope: "natal",
    label: "官禄宫天机化权",
    rawLabel: "Career Palace: Tian Ji transforms to Authority",
    traditionalInterpretation: "传统上常用于讨论策略、变化、复杂问题和对决策空间的重视。",
  },
  {
    id: "fact-ziwei-wealth-tianfu",
    system: "ziwei",
    domain: "wealth",
    scope: "natal",
    label: "财帛宫天府",
    rawLabel: "Wealth Palace: Tian Fu",
    traditionalInterpretation: "传统上常用于讨论资源管理、耐心积累和稳健配置。",
  },
  {
    id: "fact-ziwei-relationship-taiyin",
    system: "ziwei",
    domain: "relationships",
    scope: "natal",
    label: "夫妻宫太阴",
    rawLabel: "Partnership Palace: Tai Yin",
    traditionalInterpretation: "传统上常用于讨论照顾、细腻回应与情绪安全感。",
  },
  {
    id: "fact-ziwei-current-career-convergence",
    system: "ziwei",
    domain: "timing",
    scope: "current-period",
    label: "当前官禄主题集中",
    rawLabel: "Demo Career Palace signal: convergence",
    traditionalInterpretation: "演示规则把这段时间表达为减少分散、明确优先级。",
    limitations: "固定演示文案，并非真实流年计算。",
  },
  {
    id: "fact-astro-sun-gemini-eleventh",
    system: "astrology",
    domain: "identity",
    scope: "natal",
    label: "太阳双子座，第十一宫",
    rawLabel: "Sun in Gemini, 11th House",
    traditionalInterpretation: "现代占星常将其与好奇、交流、网络和多重兴趣联系起来。",
  },
  {
    id: "fact-astro-uranus-tenth",
    system: "astrology",
    domain: "career",
    scope: "natal",
    label: "天王星第十宫",
    rawLabel: "Uranus in 10th House",
    traditionalInterpretation: "现代占星常将其与非线性职业路径、改革欲和对僵化角色的敏感联系起来。",
  },
  {
    id: "fact-astro-moon-saturn-square",
    system: "astrology",
    domain: "relationships",
    scope: "natal",
    label: "月亮与土星呈四分相",
    rawLabel: "Moon square Saturn",
    traditionalInterpretation: "现代占星常用它讨论情绪表达、责任和自我保护之间的张力。",
  },
  {
    id: "fact-astro-current-saturn-focus",
    system: "astrology",
    domain: "timing",
    scope: "current-period",
    label: "当前土星主题强调边界",
    rawLabel: "Demo transit signal: Saturn and boundaries",
    traditionalInterpretation: "演示解释把它用于讨论限制、责任和对承诺的筛选。",
    limitations: "固定演示文案，并非真实行运计算。",
  },
];

export const insights: Insight[] = [
  {
    id: "insight-today-selection",
    domain: "timing",
    kind: "consensus",
    eyebrow: "今日主题",
    title: "收敛 · 选择",
    subtitle: "减少选择，比增加选择更重要",
    summary: "最近很多事情可能同时需要你的注意力。今天更适合先决定不做什么，再把精力留给真正重要的一件事。",
    evidence: [
      { factId: "fact-bazi-current-month-focus", system: "bazi", role: "primary", contribution: "把当前阶段描述为资源需要收束。" },
      { factId: "fact-ziwei-current-career-convergence", system: "ziwei", role: "primary", contribution: "同样强调优先级与减少分散。" },
      { factId: "fact-astro-current-saturn-focus", system: "astrology", role: "supporting", contribution: "从边界和承诺角度补充这一主题。" },
    ],
    reflectionPrompt: "如果今天只能保留一个承诺，你会保留哪一个？",
  },
  {
    id: "insight-career-builder-explorer",
    domain: "career",
    kind: "consensus",
    eyebrow: "事业模式",
    title: "Builder × Explorer",
    subtitle: "你需要创造，也需要持续发现新的空间",
    summary: "你可能很享受把模糊的问题变成一个可以运作的东西；但当工作只剩重复维护时，投入感会下降。自主权往往比头衔更能决定你的长期动力。",
    evidence: [
      { factId: "fact-bazi-output-structure-tension", system: "bazi", role: "supporting", contribution: "显示创造表达与结构要求需要持续协调。" },
      { factId: "fact-ziwei-career-tianji-authority", system: "ziwei", role: "primary", contribution: "强调策略、变化和决策空间。" },
      { factId: "fact-astro-uranus-tenth", system: "astrology", role: "primary", contribution: "强调非线性路径和对僵化职业角色的敏感。" },
    ],
    reflectionPrompt: "你想离开的究竟是这份工作，还是其中缺少自主空间的部分？",
  },
  {
    id: "insight-identity-adaptive-leader",
    domain: "identity",
    kind: "tension",
    eyebrow: "自我模式",
    title: "柔韧的主导者",
    subtitle: "一边适应环境，一边希望保留最终判断",
    summary: "你可能看起来很会调整，但这不等于没有主见。真正的张力在于：你愿意协作，却不喜欢长期把关键判断交给别人。",
    evidence: [
      { factId: "fact-bazi-daymaster-yi-wood", system: "bazi", role: "primary", contribution: "提供柔韧与适应的主题。" },
      { factId: "fact-ziwei-life-leadership", system: "ziwei", role: "primary", contribution: "提供自主判断与承担复杂局面的主题。" },
      { factId: "fact-astro-sun-gemini-eleventh", system: "astrology", role: "context", contribution: "补充对交流、群体和多重视角的兴趣。" },
    ],
    tensionNote: "适应和主导并不矛盾；它们可能分别出现在探索阶段和最终决策阶段。",
    reflectionPrompt: "最近哪件事让你表面配合、内心却仍想保留决定权？",
  },
  {
    id: "insight-relationships-space-safety",
    domain: "relationships",
    kind: "tension",
    eyebrow: "关系模式",
    title: "空间与安全感",
    subtitle: "亲近和独立都需要被说出来",
    summary: "你可能既重视细腻回应，也需要足够的个人空间。没有说清楚时，一方容易把沉默理解为疏远，另一方则把追问感受为压力。",
    evidence: [
      { factId: "fact-ziwei-relationship-taiyin", system: "ziwei", role: "primary", contribution: "强调照顾和情绪安全。" },
      { factId: "fact-astro-moon-saturn-square", system: "astrology", role: "primary", contribution: "强调表达情绪与自我保护之间的拉扯。" },
    ],
    tensionNote: "这不是关系好坏判断，而是一个更适合被明确协商的需求差异。",
    reflectionPrompt: "你更希望对方理解你的哪一种需要：陪伴、空间，还是更清楚的承诺？",
  },
  {
    id: "insight-wealth-stewardship",
    domain: "wealth",
    kind: "distinct-signal",
    eyebrow: "财富模式",
    title: "先配置，再扩张",
    subtitle: "稳定来自清楚的资源边界",
    summary: "这里最明显的不是冒险或保守，而是对资源用途的掌控感。先明确基本盘，再给探索留出可承受的空间，可能更符合你的节奏。",
    evidence: [
      { factId: "fact-ziwei-wealth-tianfu", system: "ziwei", role: "primary", contribution: "提供资源管理和耐心积累的主题。" },
      { factId: "fact-bazi-output-structure-tension", system: "bazi", role: "context", contribution: "补充创造投入与结构边界之间的协调。" },
    ],
    reflectionPrompt: "哪一笔资源如果先划定边界，会让你更安心地尝试新东西？",
  },
];

export const domains: LifeDomain[] = [
  { id: "identity", nameZh: "自我", nameEn: "Identity", state: "steady", pattern: "柔韧的主导者", summary: "适应力与自主判断同时存在。", insightId: "insight-identity-adaptive-leader" },
  { id: "career", nameZh: "事业", nameEn: "Career", state: "active", pattern: "Builder × Explorer", summary: "创造、策略和自主空间是关键动力。", insightId: "insight-career-builder-explorer", dimensions: [
    { label: "自主性", qualitativeValue: "very-high", internalValue: 0.9 },
    { label: "稳定需求", qualitativeValue: "medium", internalValue: 0.55 },
    { label: "探索需求", qualitativeValue: "very-high", internalValue: 0.92 },
  ] },
  { id: "wealth", nameZh: "财富", nameEn: "Wealth", state: "steady", pattern: "先配置，再扩张", summary: "资源边界比短期刺激更重要。", insightId: "insight-wealth-stewardship" },
  { id: "love", nameZh: "爱情", nameEn: "Love", state: "reflective", pattern: "慢一点说清需要", summary: "亲近感来自被理解，也来自被允许保留空间。", insightId: "insight-relationships-space-safety" },
  { id: "family", nameZh: "家庭", nameEn: "Family", state: "steady", pattern: "责任与边界", summary: "照顾别人时，也需要明确自己的承受范围。", insightId: "insight-relationships-space-safety" },
  { id: "relationships", nameZh: "关系", nameEn: "Relationships", state: "reflective", pattern: "空间与安全感", summary: "未说出口的需要容易变成误解。", insightId: "insight-relationships-space-safety" },
  { id: "creativity", nameZh: "创造力", nameEn: "Creativity", state: "emerging", pattern: "把好奇变成作品", summary: "限制选择后，创造力更容易进入持续状态。", insightId: "insight-career-builder-explorer" },
  { id: "inner-life", nameZh: "内在成长", nameEn: "Inner Life", state: "active", pattern: "给成长留出恢复期", summary: "不是继续加速，而是建立可以反复回到的节奏。", insightId: "insight-identity-adaptive-leader" },
];

export const timing: TimingPeriod = {
  id: "timing-reorientation-2026",
  title: "重新定义方向",
  start: "2026.07",
  end: "2027.02",
  nowPosition: 0.31,
  summary: "这段时间更像一次重新配置：减少分散的投入，辨认哪些承诺仍值得继续。",
  nextTransition: { date: "2027.03", title: "开始搭建新结构", summary: "把已经明确的选择变成稳定日常。" },
  signals: [
    { id: "signal-career", domain: "career", label: "事业", strength: "very-active", internalStrength: 0.88, summary: "取舍、角色边界和决策空间是当前重点。" },
    { id: "signal-relationships", domain: "relationships", label: "关系", strength: "present", internalStrength: 0.52, summary: "适合把模糊期待转成具体沟通。" },
    { id: "signal-creativity", domain: "creativity", label: "创造", strength: "active", internalStrength: 0.76, summary: "减少并行方向后，更容易形成连续作品。" },
    { id: "signal-inner", domain: "inner-life", label: "内在", strength: "active", internalStrength: 0.71, summary: "辨认哪些责任真正属于你。" },
  ],
  disclaimer: "Activation 表示演示内容中的主题强调程度，不代表好运、坏运或确定结果。",
};

export const products: Product[] = [
  { id: "product-green-aventurine", slug: "green-aventurine", category: "stone", nameEn: "Green Aventurine", nameZh: "绿东陵石", shortDescription: "一件与成长、新开始和持续培育相呼应的日常象征物。", price: "$38", palette: ["#6f836e", "#c9c8b4", "#ede7da"], elements: ["木"], intentions: ["成长", "新开始"], traditionalMeaning: "在现代水晶文化中，绿东陵石常被赋予成长、新机会和向前展开的象征意义。这些是文化与象征关联，不是可保证的功效。", dailyUse: "把它放在工作台或日记旁，在开始一天前写下今天唯一要持续培育的事情。", material: "天然石材；每件纹理与颜色会有差异（演示商品信息）", origin: "产地信息待真实供应链确认", dimensions: "约 35–50 mm（演示规格）", care: "以柔软干布清洁，避免化学清洁剂和长时间浸水。", featured: true },
  { id: "product-amethyst", slug: "amethyst", category: "stone", nameEn: "Amethyst", nameZh: "紫水晶", shortDescription: "与安静观察和专注仪式相关的象征物。", price: "$42", palette: ["#7e7188", "#c8bdc8", "#eee8df"], elements: ["水"], intentions: ["专注", "安静"], traditionalMeaning: "在现代水晶文化中常与安静、专注和反思联系，不代表医疗或心理治疗效果。", dailyUse: "放在阅读空间，作为关闭额外干扰的视觉提示。", material: "天然石材（演示商品信息）", origin: "待确认", dimensions: "约 40 mm", care: "避免长时间强光照射。", featured: false },
  { id: "product-rose-quartz", slug: "rose-quartz", category: "stone", nameEn: "Rose Quartz", nameZh: "粉晶", shortDescription: "与温柔回应和关系意图相关的象征物。", price: "$36", palette: ["#c99f9c", "#e2c8c1", "#f2eae0"], elements: ["土"], intentions: ["温柔", "关系"], traditionalMeaning: "在现代水晶文化中常与温柔和关系意图联系，不保证带来或修复一段关系。", dailyUse: "把它放在写信的空间，提醒自己先表达需要而不是推测对方。", material: "天然石材（演示商品信息）", origin: "待确认", dimensions: "约 35 mm", care: "以柔软干布清洁。", featured: false },
  { id: "product-black-tourmaline", slug: "black-tourmaline", category: "stone", nameEn: "Black Tourmaline", nameZh: "黑碧玺", shortDescription: "与边界、落地和结束工作仪式相关的象征物。", price: "$40", palette: ["#252522", "#77736a", "#d6ccbe"], elements: ["水", "土"], intentions: ["边界", "落地"], traditionalMeaning: "传统上常与保护和边界联系；Life Map 只把它作为边界仪式的象征，不作安全保证。", dailyUse: "工作结束时把它移回托盘，作为停止处理工作信息的动作提示。", material: "天然石材（演示商品信息）", origin: "待确认", dimensions: "约 45 mm", care: "轻拿轻放，避免磕碰。", featured: false },
  { id: "product-five-elements-bracelet", slug: "five-elements-bracelet", category: "bracelet", nameEn: "Your Five Elements Bracelet", nameZh: "你的五行手链", shortDescription: "把个人主题和当前意图转化为可编辑的配色与材质组合。", price: "From $88", palette: ["#496b5d", "#a44738", "#b7a276"], elements: ["五行"], intentions: ["日常仪式", "个人化"], traditionalMeaning: "未来版本会透明展示设计规则，并允许用户调整；不会宣称手链改变命运。", dailyUse: "佩戴时选择一个当天想实践的主题，而不是期待物品产生确定结果。", material: "概念商品；材质待确认", origin: "待确认", dimensions: "按尺寸定制", care: "待真实材质确认后提供。", featured: false },
  { id: "product-chart-art", slug: "personal-life-map-art", category: "chart-art", nameEn: "Personal Life Map Art", nameZh: "个人命盘艺术画", shortDescription: "把四柱、圆盘与五行结构转化为克制的个性化艺术作品。", price: "From $64", palette: ["#f5f1e8", "#171714", "#496b5d"], elements: ["五行"], intentions: ["创造", "纪念"], traditionalMeaning: "以结构化命盘事实为视觉素材，定位为个性化艺术而非效果型产品。", dailyUse: "作为个人故事和反思主题的视觉纪念。", material: "数字文件或艺术纸印刷（概念商品）", origin: "按需制作", dimensions: "多种尺寸", care: "纸质版本避免潮湿和强光。", featured: false },
];

export const recommendation: Recommendation = {
  id: "recommendation-growth-aventurine",
  productId: "product-green-aventurine",
  headline: "与你的「成长」主题呼应",
  summary: "这件物品把命盘中的成长主题、当前的收束阶段和你对新开始的意图连接在一起。它是一种象征选择，不是改变结果的工具。",
  reasons: [
    { id: "reason-profile", source: "birth-profile", label: "个人主题 · Wood", explanation: "演示命盘把木描述为需要被有意识培育的主题，而不是需要被修复的缺陷。", factId: "fact-bazi-wood-relative-low" },
    { id: "reason-timing", source: "current-timing", label: "当前阶段 · 收束", explanation: "当前主题建议先减少分散投入，再选择值得持续生长的方向。", factId: "fact-bazi-current-month-focus" },
    { id: "reason-intention", source: "user-intention", label: "你的意图 · 新开始", explanation: "你在演示流程中选择了“新开始”，因此推荐更强调成长和培育。" },
  ],
  nonCommercialPractice: { title: "先试一个不需要购买的仪式", instruction: "写下一个未来七天愿意持续培育的小行动，并划掉一个暂时不做的方向。" },
  disclaimer: "水晶和元素的关联来自传统及现代象征文化，不是科学功效或结果保证。",
};

const evidence = {
  career: [
    { factId: "fact-bazi-output-structure-tension", system: "bazi" as const, role: "supporting" as const, contribution: "提示表达和结构之间需要协调。" },
    { factId: "fact-ziwei-career-tianji-authority", system: "ziwei" as const, role: "primary" as const, contribution: "强调策略变化和决策空间。" },
    { factId: "fact-astro-uranus-tenth", system: "astrology" as const, role: "primary" as const, contribution: "强调非线性职业路径。" },
  ],
  relationship: [
    { factId: "fact-ziwei-relationship-taiyin", system: "ziwei" as const, role: "primary" as const, contribution: "强调情绪回应和安全感。" },
    { factId: "fact-astro-moon-saturn-square", system: "astrology" as const, role: "primary" as const, contribution: "强调表达与保护之间的张力。" },
  ],
};

export const askResponses: AskResponse[] = [
  { id: "ask-career-transition", category: "career-transition", suggestedPrompt: "我现在的职业处于什么阶段？", title: "你可能正在从“证明能做”转向“选择值得做”", directAnswer: "现在最值得注意的，不一定是立刻离开或留下，而是你对自主空间、重复程度和长期投入的标准正在变得更清楚。", kind: "consensus", sections: [{ heading: "三个体系共同出现的主题", body: "变化本身不是唯一重点。更一致的主题是：把探索能力放进一个拥有真实决策空间的结构里。", evidence: evidence.career }], reflectionQuestion: "如果不换公司，你最希望先改变当前角色里的哪一个结构条件？", relatedDomain: "career", disclaimer: "这是基于演示命盘事实的反思性解释，不是职业或财务建议。" },
  { id: "ask-relationship-pattern", category: "relationship-pattern", suggestedPrompt: "为什么我和亲近的人总会重复类似的冲突？", title: "冲突可能发生在“需要靠近”和“需要空间”的翻译上", directAnswer: "你可能不是不重视关系，而是在压力下更倾向先整理自己；对方却可能把这种暂停理解为撤离。", kind: "tension", sections: [{ heading: "关系中的两种需要", body: "一条线索强调细腻回应与安全感，另一条线索强调责任压力下的自我保护。重点不是哪一方正确，而是暂停需要被提前说明。", evidence: evidence.relationship }], reflectionQuestion: "下一次需要空间时，你能否同时说明：需要多久、之后何时回来继续谈？", relatedDomain: "relationships", disclaimer: "这是反思提示，不替代伴侣沟通、咨询或安全支持。" },
  { id: "ask-new-beginning", category: "new-beginning", suggestedPrompt: "今年适合开始新的事情吗？", title: "可以先开始，但把“开始”定义得更小", directAnswer: "演示信号没有提供简单的是或否。它更支持先缩小范围，用一个可持续的小实验代替同时开启多个方向。", kind: "consensus", sections: [{ heading: "为什么先做小实验", body: "当前主题同时强调收束、边界和清晰优先级。新开始不需要被取消，但需要明确的停止条件和复盘时间。", evidence: insights[0].evidence }], reflectionQuestion: "什么是你可以在七天内完成、同时不要求自己承诺一整年的第一步？", relatedDomain: "creativity", disclaimer: "这是反思性解释，不是对项目结果的保证。" },
  { id: "ask-internal-tension", category: "internal-tension", suggestedPrompt: "我的命盘里最矛盾的地方是什么？", title: "你既会适应，也不愿放弃最终判断", directAnswer: "外在的灵活和内在的主导感可以同时存在。真正消耗你的，往往不是变化，而是长期适应一个自己无法影响的结构。", kind: "tension", sections: [{ heading: "张力从哪里来", body: "八字演示事实强调柔韧，紫微演示事实强调自主承担，西方占星补充对多重视角和群体连接的兴趣。", evidence: insights[2].evidence }], reflectionQuestion: "最近一次妥协中，你让出的是做法，还是连最终判断也一起让出了？", relatedDomain: "identity", disclaimer: "这是基于演示事实的反思性解释。" },
  { id: "ask-general", category: "general", suggestedPrompt: "我现在最值得关注什么？", title: "先把问题缩小一点", directAnswer: "我可以结合演示命盘讨论事业、关系、新开始或内在张力。问题越具体，回答越容易和可见证据连接。", kind: "distinct-signal", sections: [], reflectionQuestion: "这件事最让你卡住的是选择、关系、时间，还是不知道自己真正想要什么？", disclaimer: "Phase 1 使用固定演示回答，不会调用实时 AI。" },
];

export const iching: IChingResult = {
  id: "iching-demo-63-line-2",
  sampleQuestion: "我是否应该接受这个新的工作机会？",
  lines: [
    { position: 1, value: 7, polarity: "yang", moving: false, coinFaces: ["heads", "heads", "tails"] },
    { position: 2, value: 6, polarity: "yin", moving: true, coinFaces: ["tails", "tails", "tails"] },
    { position: 3, value: 7, polarity: "yang", moving: false, coinFaces: ["heads", "heads", "tails"] },
    { position: 4, value: 8, polarity: "yin", moving: false, coinFaces: ["heads", "tails", "tails"] },
    { position: 5, value: 7, polarity: "yang", moving: false, coinFaces: ["heads", "heads", "tails"] },
    { position: 6, value: 8, polarity: "yin", moving: false, coinFaces: ["heads", "tails", "tails"] },
  ],
  primary: { number: 63, nameZh: "既济", nameEn: "After Completion" },
  relating: { number: 5, nameZh: "需", nameEn: "Waiting" },
  movingLineLabels: ["六二"],
  originalTextLabel: "六二",
  originalTextExcerpt: "妇丧其茀，勿逐，七日得。",
  plainLanguage: "事情看似已经具备条件，但并不要求你立刻追赶所有缺失的信息。先稳定位置，等待关键条件自然显现，可能比仓促补齐更重要。",
  applicationToQuestion: "这个卦不提供简单的接受或拒绝。它提醒你先确认缺少的关键条件——例如决策权、团队边界或时间承诺——是否会在短期内变得清楚。",
  reflectionPrompt: "如果给自己七天，你最需要等到哪一项事实变清楚？",
  disclaimer: "I Ching 在这里是一种传统反思实践，不是对结果的保证，也不替代职业或财务判断。",
};
