import { sql } from "drizzle-orm";
import { blob, check, index, integer, sqliteTable, text, uniqueIndex } from "drizzle-orm/sqlite-core";

export const reportJobs = sqliteTable("report_jobs", {
  id: text("id").primaryKey(),
  status: text("status").notNull(),
  productKey: text("product_key").notNull(),
  expectedVariantGid: text("expected_variant_gid").notNull(),
  expectedVariantNumericId: text("expected_variant_numeric_id").notNull(),
  expectedAmountCents: integer("expected_amount_cents").notNull(),
  expectedCurrency: text("expected_currency").notNull(),
  r2Key: text("r2_key").unique(),
  pdfSha256: text("pdf_sha256"),
  pdfSizeBytes: integer("pdf_size_bytes"),
  pdfPageCount: integer("pdf_page_count"),
  reportSchemaVersion: text("report_schema_version").notNull(),
  jobCapabilityHash: text("job_capability_hash"),
  checkoutUrlCiphertext: blob("checkout_url_ciphertext", { mode: "buffer" }),
  checkoutUrlNonce: blob("checkout_url_nonce", { mode: "buffer" }),
  checkoutLeaseId: text("checkout_lease_id"),
  checkoutLeaseStartedAt: integer("checkout_lease_started_at"),
  shopifyOrderId: text("shopify_order_id").unique(),
  shopifyOrderNumber: text("shopify_order_number"),
  shopifyLineItemId: text("shopify_line_item_id").unique(),
  buyerEmailHmac: text("buyer_email_hmac"),
  refundedCents: integer("refunded_cents").notNull().default(0),
  statusReason: text("status_reason"),
  createdAt: integer("created_at").notNull(),
  checkoutAt: integer("checkout_at"),
  paidAt: integer("paid_at"),
  deliveredAt: integer("delivered_at"),
  expiresAt: integer("expires_at").notNull(),
  terminalAt: integer("terminal_at"),
  updatedAt: integer("updated_at").notNull(),
  purgeLeaseId: text("purge_lease_id"),
  purgeStartedAt: integer("purge_started_at"),
  version: integer("version").notNull().default(0),
}, (table) => [
  check("report_jobs_status_check", sql`${table.status} IN ('pending','checkout_created','paid','delivered','review_required','abandoned','cancelled','refunded','expired')`),
  check("report_jobs_product_check", sql`${table.productKey} = 'full-report-v1'`),
  check("report_jobs_amount_check", sql`${table.expectedAmountCents} = 200`),
  check("report_jobs_currency_check", sql`${table.expectedCurrency} = 'USD'`),
  check("report_jobs_size_check", sql`${table.pdfSizeBytes} IS NULL OR ${table.pdfSizeBytes} BETWEEN 1024 AND 5242880`),
  check("report_jobs_pages_check", sql`${table.pdfPageCount} IS NULL OR ${table.pdfPageCount} = 10`),
  index("report_jobs_expiry_idx").on(table.status, table.expiresAt),
  index("report_jobs_recovery_idx").on(table.shopifyOrderNumber, table.buyerEmailHmac),
]);

export const webhookDeliveries = sqliteTable("shopify_webhook_deliveries", {
  webhookId: text("webhook_id").primaryKey(),
  eventId: text("event_id"),
  topic: text("topic").notNull(),
  shopDomain: text("shop_domain").notNull(),
  shopifyOrderId: text("shopify_order_id"),
  jobId: text("job_id").references(() => reportJobs.id, { onDelete: "set null" }),
  payloadSha256: text("payload_sha256").notNull(),
  status: text("status").notNull(),
  attemptCount: integer("attempt_count").notNull().default(1),
  errorCode: text("error_code"),
  receivedAt: integer("received_at").notNull(),
  processingStartedAt: integer("processing_started_at").notNull(),
  processedAt: integer("processed_at"),
}, (table) => [
  check("webhook_topic_check", sql`${table.topic} IN ('orders/paid','orders/cancelled','refunds/create')`),
  check("webhook_status_check", sql`${table.status} IN ('processing','processed','rejected','retryable')`),
  index("webhook_event_idx").on(table.eventId),
  uniqueIndex("webhook_event_topic_unique").on(table.eventId, table.topic),
  index("webhook_retention_idx").on(table.processedAt),
]);

export const reportTokens = sqliteTable("report_tokens", {
  id: text("id").primaryKey(),
  jobId: text("job_id").notNull().references(() => reportJobs.id, { onDelete: "cascade" }),
  tokenHash: text("token_hash").notNull(),
  purpose: text("purpose").notNull(),
  maxUses: integer("max_uses").notNull(),
  useCount: integer("use_count").notNull().default(0),
  createdAt: integer("created_at").notNull(),
  expiresAt: integer("expires_at").notNull(),
  usedAt: integer("used_at"),
  revokedAt: integer("revoked_at"),
}, (table) => [
  check("report_tokens_purpose_check", sql`${table.purpose} IN ('email_link','download_session')`),
  check("report_tokens_uses_check", sql`${table.maxUses} BETWEEN 1 AND 5`),
  uniqueIndex("report_tokens_hash_idx").on(table.tokenHash),
  index("report_tokens_expiry_idx").on(table.expiresAt),
]);

export const deliveryOutbox = sqliteTable("delivery_outbox", {
  id: text("id").primaryKey(),
  jobId: text("job_id").notNull().references(() => reportJobs.id, { onDelete: "cascade" }),
  tokenId: text("token_id").notNull().references(() => reportTokens.id, { onDelete: "cascade" }),
  kind: text("kind").notNull(),
  generation: integer("generation").notNull().default(1),
  recipientCiphertext: blob("recipient_ciphertext", { mode: "buffer" }),
  recipientNonce: blob("recipient_nonce", { mode: "buffer" }),
  encryptionKeyVersion: integer("encryption_key_version").notNull(),
  providerIdempotencyKey: text("provider_idempotency_key").notNull(),
  status: text("status").notNull(),
  attempts: integer("attempts").notNull().default(0),
  nextAttemptAt: integer("next_attempt_at").notNull(),
  leaseId: text("lease_id"),
  leaseStartedAt: integer("lease_started_at"),
  lastErrorCode: text("last_error_code"),
  createdAt: integer("created_at").notNull(),
  sentAt: integer("sent_at"),
}, (table) => [
  check("delivery_kind_check", sql`${table.kind} IN ('initial_delivery','access_recovery')`),
  check("delivery_status_check", sql`${table.status} IN ('pending','sending','sent','failed','expired')`),
  uniqueIndex("delivery_provider_key_idx").on(table.providerIdempotencyKey),
  uniqueIndex("delivery_generation_idx").on(table.jobId, table.kind, table.generation),
  index("delivery_outbox_due_idx").on(table.status, table.nextAttemptAt),
]);

export const recoveryRateLimits = sqliteTable("recovery_rate_limits", {
  keyHmac: text("key_hmac").primaryKey(),
  windowStartedAt: integer("window_started_at").notNull(),
  attemptCount: integer("attempt_count").notNull(),
  expiresAt: integer("expires_at").notNull(),
});
